### PR TITLE
Fix horizontal margin of "Look at the following issues and get hacking" on mobile devices

### PR DESCRIPTION
**Pull request by fischeversenker**
#### Ticket
No open ticket for this issue.

#### Issue
Currently the section "Look at the following issues and get hacking" is the only thing on the page that has no horizontal margin on mobile devices. This removes the obsolete `flex` classes and adds the same classes that are on the other sections on the page.

#### Usage Changes
None.

#### Screenshot
Before;
hacktoberfestchecker jenko me_user_fischeversenker

After:
hacktoberfestchecker jenko me_user_fischeversenker (1)

### CODE REVIEW

**Comment by fischeversenker** [comment]
Uagh. I just realized that PRs only count for Hacktoberfest if opened after/on Oct. the 1st. Will close this one and open it anew on Oct 1st :+1:

**Comment by jenkoian** [comment]
@fischeversenker working on a new version for Tuesday 👍

**Comment by fischeversenker** [comment]
Nice! I like the facelift! :+1:
Will reopening this PR count as a PR for Hacktoberfest?

**Comment by jenkoian** [comment]
Hi @fischeversenker is this still as issue? I can't seem to reproduce?

**Pull request closed without merging**
