### PR TITLE
Live hacktoberfest issue ticker #23

### PR DESCRIPTION
**Pull request by Ne3l**
Finds issues with hacktoberfest label and display them below.

The presentation of issues can be improved also i'm not sure if using github label colors was a good idea.

### CODE REVIEW

**Comment by jenkoian** [comment]
Thanks for this! Here's my feedback (mostly revolves around look and feel):

* Site uses [Foundation](http://foundation.zurb.com/) so please leverage some of that for the styles. For example there is a [label component](http://foundation.zurb.com/sites/docs/label.html) which you can use for displaying the labels. 

* I'd say display the issues in two columns underneath the search bar with a smaller font to make it a bit subtler. I also think we should display the issues from the get go rather than on button click. 

* I'd make the titles clickable rather than the description. Also, the labels should be clickable too. 

* Not sure whether to change it to descending created date or not. On one hand it'd be good to show the latest issues (then in future we could have some kind of real time check which could pop new issues to the top, maybe) but on the other hand I think it'd be neat if the old issues get addressed, so am up for opinions on this.

**Comment by Ne3l** [comment]
Thanks for the feedback, i agree with the most but:

- If labels should be clickable what should the click action do?

- For display the issues i think it would be a good idea to dispose some kind of filters such a order asc/desc, language, labels, etc...

**Comment by jenkoian** [comment]
Cheers @Ne3l and @games647 - it's definitely getting there but still feels a little clunky. 

* I think the avatars are too big at the mo and they should be round to match the avatar on the result of the check. 
* In general I think it should be a bit subtler, it's a secondary feature after the main feature which is the check, so I'd bring the size of the font and everything down a little. Particularly the title (the 'Help other projects - Total: 4065' bit). 
* Labels I think should go to the issues of the project filtered by the label you've clicked.
* With regards filtering, I'm not sure, think it'd be doing too much then. See the main benefit in this just to give a user a quick heads up of potential contributions, they can go through to github then to drilldown further.

**Comment by jenkoian** [comment]
Looking good! I've made a few tweaks, mostly for the responsive stuff and pushed up to a branch here: https://github.com/jenkoian/hacktoberfest-checker/commit/67f87d4508840e6734d52774800fd08e649993de if you're happy with those changes, you can either open up your branch so I can write to it (e.g. https://github.com/blog/2247-improving-collaboration-with-forks) or I'll PR that branch I just pushed (it has your commits so your collaboration should remain in tact). Cheers!

**Comment by jenkoian** [comment]
Merged in https://github.com/jenkoian/hacktoberfest-checker/pull/47 thanks for all your help!

**Pull request closed without merging**
