### PR TITLE
Fix : Duplicate block of css in style.css

### PR DESCRIPTION
**Pull request by deepak-kamath**
Hey @jenkoian! A duplicate block of CSS has been removed in style.css. Duplicate blocks (Lines 46-64) 

repeatedblock

### CODE REVIEW

**Comment by jenkoian** [comment]
Hmm thanks, are you able to run `npm run tailwing-gen` too which should update index.css.

**Comment by deepak-kamath** [comment]
Hey @jenkoian, yes, `npm run tailwind-gen` seems to be working and updating index.css but a commit after that gives me an error relating to Code styling issues. On running `npm run prettier-fix`, I see a lot of files modified. Please advice if I should commit all those changes.

**Comment by jenkoian** [comment]
@deepak-kamath can you push to this PR so I can take a look?

**Comment by deepak-kamath** [comment]
Hey @jenkoian, I've pushed after running `npm run tailwind-gen` .  I see changes only in index.css and style.css . Looks alright now.

**Comment by jenkoian** [comment]
Thanks @deepak-kamath

**Pull request merged**
