### PR TITLE
(ES5) Separates concerns into modules for easier testing

### PR DESCRIPTION
**Pull request by josecanhelp**
Uses ES5 Syntax

We can wait until everyone submits their PRs for hacktoberfest before merging. This will help modularize the codebase for easier testing and keeps the ES5 syntax.

### CODE REVIEW

**Comment by jenkoian** [comment]
Thanks @josecanhelp is #61 obsolete now? If so please close. This looks good, do you mean picking up the conflict, will then look to get this merged 👍

**Comment by josecanhelp** [comment]
@jenkoian Yes, I closed out #61. I also fixed the merge conflict for this PR. Thanks.

**Comment by jenkoian** [comment]
Sorry for the delay, finally got round to checking this out. All looks good, I seem to have spotted a small issue with it though. When I try it out locally the open issues ('Help other projects') bit doesn't load on the first load, it's fine on subsequent loads but doesn't load in that first hit. Now in production it's presumably a non issue, as it's only the first load, but still it seems like an issue we should get fixed before merging. Can you replicate this also? Do you think it's something you could look into?

**Comment by josecanhelp** [comment]
@jenkoian I'll definitely look into this. No worries on the delay. I totally get there are higher priority things going on. I'll check it out this weekend.

**Comment by jenkoian** [comment]
Cheers for this, have updated the app for 2017 so closing this, feel free to re-submit! 😃

**Pull request closed without merging**
