### PR TITLE
Updated the tailwind css package version

### PR DESCRIPTION
**Pull request by PGNITH**
I've Succesfully Updated the tailwind css package from version 1.9.4 to the current latest version 2.2.16

### CODE REVIEW

**Comment by jenkoian** [comment]
Does it work? Have you tested it? Any new features we unlock? Also, may be worth re-opening in October if you want it to count towards your stats? :)

**Comment by PGNITH** [comment]
Yeah it works fine.
It has a lot of new bug fixes like:
          Improved accessibility of default link focus styles in Firefox 
          Fixed animation variants corrupting keyframes rules
          Ignore escaped commas when splitting selectors to apply prefixes
          Nesting: Maintain PostCSS node sources when handling @apply
          Fix support for animation lists
           Fix arbitrary value support for object-position utilities
          Abort watcher if stdin is closed to avoid zombie processes
          Ignore arbitrary values with unbalanced brackets
And there are much more fixes which the previous version 1.9.4 didn't have.

**Comment by jenkoian** [comment]
@PGNITH thanks, I think there's a few extra things we'd need to take care of:

* We'd need to update the [docker image](https://github.com/jenkoian/hacktoberfest-checker/blob/master/Dockerfile#L1) (and the README) to be node 12 (or poss 14)  https://tailwindcss.com/docs/upgrading-to-v2#upgrade-to-node-js-12-13-or-higher

* Need to make sure our colour palette remains in tact https://tailwindcss.com/docs/upgrading-to-v2#configure-your-color-palette-explicitly

* Check font size remains in tact https://tailwindcss.com/docs/upgrading-to-v2#configure-your-font-size-scale-explicitly

* Ensure postcss and autoprefixer are updated also https://tailwindcss.com/docs/upgrading-to-v2#install-tailwind-css-v2-0-and-post-css-8

* Ensure the `package-lock.json` is updated too

**Comment by Widi-ps** [comment]
why when I write `$ npm run tailwind-gen` it appears like this. Is there something wrong?
image

**Comment by jenkoian** [comment]
@Widi-ps on this branch or master?

**Comment by Widi-ps** [comment]
@jenkoian I think on master, I clone this repo then I started to run the installation but when `$ npm run tailwind-gen` it appears like that. Should I change into branches?

**Comment by jenkoian** [comment]
@Widi-ps it seemed to work for me ok, make sure you're on a supported version of node by using `nvm` (`nvm use`)

**Comment by Widi-ps** [comment]
@jenkoian it still doesn't work, even though I've used nvm lts. is there no error in postcss? or maybe there is another thing that I've missed because at the results something missing with )


image


image

**Comment by jenkoian** [comment]
@Widi-ps I suspect it's a Windows thing or something, this is what it does under the hood:

`node ./node_modules/.bin/postcss ./src/style.css -o ./src/index.css`

So whatever the equivalent of that is that runs ok on your system? I think it could prob be simplified to `postcss ./src/style.css -o ./src/index.css` within `package.json` because npm will add the node_modules to the path implicitly.

**Comment by jenkoian** [comment]
@Widi-ps please try this branch https://github.com/jenkoian/hacktoberfest-checker/pull/594 and if it still doesn't work, try the suggestion in the PR description

**Pull request closed without merging**
