### PR TITLE
Feat add nvm support

### PR DESCRIPTION
**Pull request by slabruyere**
Fixes issue https://github.com/jenkoian/hacktoberfest-checker/issues/239

Changes: 
* Adding nvm support with `.nvmrc`, expected version is latest
* Adding an npm script in `package.json` to update Node version in `README.md` to local Node version (`node -v`)
* Adding a pre-commit git hook to check those versions match
* Adding an npm script in `package.json` to copy githooks to `.git/hooks`

### CODE REVIEW

**Comment by jenkoian** [comment]
Thanks for this, looks really useful. I got the following error when trying this locally:

```
> hacktoberfest-checker@3.0.1 update-node-version /Users/ian/Code/hacktoberfest-checker
> sed -i '' 's/v[^0-9]*[0-9]*[.][0-9]*[.][0-9]*[0-9A-Za-z-]*/'$(node -v)'/g' README.md

sed: can't read s/v[^0-9]*[0-9]*[.][0-9]*[.][0-9]*[0-9A-Za-z-]*/v6.11.5/g: No such file or directory

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/ian/.nvm/versions/node/v6.11.5/bin/node" "/Users/ian/.nvm/versions/node/v6.11.5/bin/npm" "run" "update-node-version"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hacktoberfest-checker@3.0.1 update-node-version: `sed -i '' 's/v[^0-9]*[0-9]*[.][0-9]*[.][0-9]*[0-9A-Za-z-]*/'$(node -v)'/g' README.md`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the hacktoberfest-checker@3.0.1 update-node-version script 'sed -i '' 's/v[^0-9]*[0-9]*[.][0-9]*[.][0-9]*[0-9A-Za-z-]*/'$(node -v)'/g' README.md'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hacktoberfest-checker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sed -i '' 's/v[^0-9]*[0-9]*[.][0-9]*[.][0-9]*[0-9A-Za-z-]*/'$(node -v)'/g' README.md
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hacktoberfest-checker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hacktoberfest-checker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ian/Code/hacktoberfest-checker/npm-debug.log
```

I suspect it's because of this (if I run `nvm install`) 

```
Found '/Users/ian/Code/hacktoberfest-checker/.nvmrc' with version <lts/*>
Version 'lts/*' not found - try `nvm ls-remote` to browse available versions.
```

Is there a way to have nvm set a lts version automatically or anything?

**Comment by slabruyere** [comment]
Oh, sorry about that ! Hmm... I'm running on MacOs and it works fine.
The output I get for `nvm install` is the following:
```
nvm install
Found '/Users/slabruyere/Development/hacktoberfest-checker/.nvmrc' with version <lts/*>
v6.11.5 is already installed.
Now using node v6.11.5 (npm v3.10.10)
```

I had issues with `sed -i` at first because it was not allowing me *not* to pass it an extension argument (cf. http://www.grymoire.com/Unix/Sed.html#uh-62h). That's why I went for `sed -i ''`

What platform are you running on ?

**Comment by jenkoian** [comment]
ah could be a sed thing, I have installed gnu sed (`brew install gnu-sed`) on my machine due to issues I had with the BSD sed installed on macs by default previously.

**Comment by slabruyere** [comment]
Ok 😁 I think we're on the right track !
Does it work if you remove the `''` locally ?
If we want to avoid using `sed`, I can write a node script to perform the replace.
But I'm also using sed for the `pre-commit` script. Can you tell me the output (if any) you get locally for `./scripts/githooks/pre-commit` ?

**Comment by slabruyere** [comment]
I added a commit with an node script to perform the version replace ;)

**Comment by jenkoian** [comment]
Closing in prep for 2018 rewrite.

**Pull request closed without merging**
