### PR TITLE
Add lock files to .gitignore

### PR DESCRIPTION
**Pull request by lex111**
Changes: Add NPM lock files to .gitignore

### CODE REVIEW

**Comment by jenkoian** [comment]
Thanks @lex111 !

**Comment by jenkoian** [comment]
@lex111 actually, I'm not sure we want to do this. This is an app, not a library, I feel the lock file(s) should be committed.

**Comment by lex111** [comment]
@jenkoian what's the difference?

**Comment by jenkoian** [comment]
@lex111 https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for plug deployment to heroku depends on a yarn.lock being present.

**Comment by lex111** [comment]
@jenkoian ok, thanks, I created a PR #177 with a gitignore rollback, and using yarn in the README and Docker file.

**Pull request merged**
