### PR TITLE
fix: Change back to 1 week review period

### PR DESCRIPTION
**Pull request by vrabe**
The review period is 7 days this year. See [here](https://hacktoberfest.com/participation/#pr-mr-details).
However the review period starts when a PR/MR is merged, approved, or labeled as "hacktoberfest-accepted". I don't know how to determine the review period is ended or not.

### CODE REVIEW

**Comment by jenkoian** [comment]
So yeah I guess the main difference with this is that we're doing 7 days since PR creation where as Digital Ocean do 7 days since merge/PR approval right?

**Comment by vrabe** [comment]
Yes. I can't figure out how to trace when a pr got approve or labeled "hacktoberfest-accepted".

**Comment by vimode** [comment]
@jenkoian This is my understanding from the [participation page](https://hacktoberfest.com/participation/)
When a PR is raised in an appropriate repo (hacktoberfest topic or label), it goes in the 7-day waiting period. In those 7 days the PR must be 
a) withing the event date. be in public and unachived repo
b) merged by the maintainer ( anytime in those 7 day period) 
c) not marked as spam or invalid
If it passes all the checks in that 7 day review period it gets counted. 

I hope I didn't missing anything, did I?

@vrabe I don't think it really hinges on that single fact of being labelled `hacktoberfest-accepted`. its not necessary that it should be labeled, the repo can have the `hacktoberfest` topic and its fine it seems. The [participation](https://hacktoberfest.com/participation/) page says 
> Your PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label.

**Comment by vrabe** [comment]
@vimode Because 7 days count starts at a pr is merged, approved, or labeled as "hacktoberfest-accepted".(This condition will usually be the last one to be satisfied.) Some maintainers may give a "hacktoberfest-accepted" label first and postpone review. In that case we don't know when the review period starts.

**Comment by jenkoian** [comment]
> Yes. I can't figure out how to trace when a pr is got approve or labeled "hacktoberfest-accepted".

This is pseudo code but should be able to do something like...

`const isApproved = pr.mergedDate > sevenDaysAgo || pr.hacktoberFestLabelEventAdded > sevenDaysAgo` || pr.approvedDate > sevenDaysAgo`

I think the hardest in amongst that is the label event. Need to find out how we can grab that, from github and gitlab. I assume it is possible as DO would need to check this via the APIs also.

**Comment by vrabe** [comment]
I think they have db to store pr states. I don't know how to do it without db.

**Comment by vrabe** [comment]
I asked on official Discord server. Matt suggested that we can check [this](https://docs.github.com/en/graphql/reference/unions#pullrequesttimelineitem). But it's in GraphQL API.

**Comment by jenkoian** [comment]
Ah nice, thanks for asking @vrabe - I'm not going to have the capacity to look at adding this, but would happily take a contribution. Did you want to take it on in this ticket? Else I can add a new ticket for anyone who might want to.

We currently use the octokit/rest library, but hopefully not too much effort to add https://www.npmjs.com/package/@octokit/graphql as well. 

Not sure if this was mentioned in the discord or not, but need to think about how this would get handled on gitlab too

**Comment by vrabe** [comment]
@jenkoian, I can't do it right now. So feel free to create a new issue for this. If no one do it and I am free then, I'll work on this.

I didn't ask about gitlab. I searched gitlab doc and couldn't find similar api.

**Comment by vimode** [comment]
@jenkoian 
I think for now you should accept this PR till we figure out how to make it work *accurately* because currently its counting 7 days too long anyway. 

IMO, its better to show more accepted than show more pending(which looks like stale data.)

I will try to dig in to the queries and try to work on how the timeline queries, but you also mentioned you want to replace the currently used octakit rest library with graphql library instead. I will try to put some time into it and work on it, but please feel free to open an issue with it so others can work on it too as it turns out its more complicated than that as someone has to figure out how to incorporate the gitlab events too.  It might end up being a compromise.

**Comment by jenkoian** [comment]
@vimode agreed, merging now.

**Comment by jenkoian** [comment]
Thanks @vrabe

**Pull request merged**
