### PR TITLE
Change status pull request

### PR DESCRIPTION
**Pull request by urmauur**
Solve #425 

Screen Shot 2020-10-02 at 20 54 41

### CODE REVIEW

**Comment by urmauur** [comment]
Helo any update this regarding PR ? @

**Comment by jenkoian** [comment]
@urmauur noticed this was very similar to https://github.com/jenkoian/hacktoberfest-checker/pull/430 so was going to give @hardikmodi1 come back on that first. One feedback for both PRs is I think we need to make the pill and text a bit smaller.

**Comment by urmauur** [comment]
> @urmauur noticed this was very similar to #430 so was going to give @hardikmodi1 come back on that first. One feedback for both PRs is I think we need to make the pill and text a bit smaller.

Screen Shot 2020-10-04 at 23 04 07

sure, thanks for clarify, also updated from your feedback 👌🏻

**Comment by jenkoian** [comment]
Hey thanks @urmauur gonna go with https://github.com/jenkoian/hacktoberfest-checker/pull/430 as it was first, but will tag this as `hacktoberfest-accepted` so you get the cred 👍

**Comment by urmauur** [comment]
thanks @jenkoian 😎👌🏻

**Pull request closed without merging**
