### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by elite16op**
issue in a:hover
fixed the link fade issue

### CODE REVIEW

**Comment by jenkoian** [comment]
Can you provide a screenshot or video of what has changed here and what affect it has? Not sure I follow

**Comment by elite16op** [comment]
[screen-capture (2).webm](https://user-images.githubusercontent.com/111674354/195069559-e719035c-9d3a-4b50-8124-5d7c9c984c4d.webm)

it fixes this issue

**Comment by jenkoian** [comment]
Thanks, please see this: https://github.com/jenkoian/hacktoberfest-checker#changing-styling

**Comment by elite16op** [comment]
what to add here in google analytics 
Screenshot (254)

**Pull request closed without merging**
