### PR TITLE
Added FAQs

### PR DESCRIPTION
**Pull request by hjaintech**
Added the FAQ section

### CODE REVIEW

**Comment by hjaintech** [comment]
@jenkoian This commit resolves the issue #367 . Please review and merge.

**Comment by jenkoian** [comment]
Thanks @hjaintech I'm looking for something on the actual app not just the README.

**Comment by DirtySoc** [comment]
> Thanks @hjaintech I'm looking for something on the actual app not just the README.

Maybe you could add an issue for creating a contributing FAQ in the readme?

**Comment by jenkoian** [comment]
Thanks for your efforts but going to close this in favour of https://github.com/jenkoian/hacktoberfest-checker/pull/372

**Pull request closed without merging**
