### PR TITLE
Correction 2017

### PR DESCRIPTION
**Pull request by Humeira**
According to this tweet 

https://twitter.com/digitalocean/status/914144872420003840?ref_src=twsrc%5Etfw

Start date should be 1st October 2017

### CODE REVIEW

**Comment by jenkoian** [comment]
This is probably something we will need to check with @digitalocean about but the current date range is based off this commit from a former 'official' checker: https://github.com/erikaheidi/hacktoberfest-verify/commit/7807e0db892f7cb82a60cfc612c7b1e8312ef582 

I think it's to allow for different timezones.

I'll close this for now and try and seek clarification from @digitalocean, cheers 👍

**Comment by Humeira** [comment]
Alright no problem @jenkoian 

Cheers 👍

**Comment by Humeira** [comment]
I just came across Digital Ocean's blogpost

The date is 1-31 October

image

https://blog.digitalocean.com/hacktoberfest-2017/

**Comment by jenkoian** [comment]
@Humeira yep, it's just hard to work out when that is across the globe due to (bloody) timezones...am open to better ways of handling it, but don't think we can simply do 2017-10-01 00:00:00 - 2017-10-31 23:59:59 unfortunately.

**Pull request closed without merging**
