### PR TITLE
Added the attributes in input tag

### PR DESCRIPTION
**Pull request by simson1**

### CODE REVIEW

**Comment by jenkoian** [comment]
Please explain?

**Comment by simson1** [comment]
> 
> 
> Please explain?

You have to add attributes like autocorrect and autocapitalize  in the input tag.

**Comment by jenkoian** [comment]
I believe they were turned off for a reason, see https://github.com/jenkoian/hacktoberfest-checker/pull/328

**Comment by simson1** [comment]
> 
> 
> I believe they were turned off for a reason, see #328

yeah. sorry about that

**Pull request closed without merging**
