### PR TITLE
Update Open graph thumbnail for 2018

### PR DESCRIPTION
**Pull request by ismailuddin**
Fixes issue # 282

Changes: Updated Open Graph image to be inline with 2018 branding.

Screenshots for the change:
image

### CODE REVIEW

**Comment by jenkoian** [comment]
@ismailuddin I love that, however, I'm not sure Digital Ocean will allow me to use their image. Would you mind just using a plain logo like the old one?

**Comment by ismailuddin** [comment]
Hmm, good point... Ammending now!

**Comment by jenkoian** [comment]
Thanks! I find it a bit busy, are you able to remove the stains in the background and capitalise hacktoberfest and checker?

**Comment by ismailuddin** [comment]
Yup can do, will change it by end of day!

**Comment by jenkoian** [comment]
Thanks!

**Pull request merged**
