### PR TITLE
Use pushState

### PR DESCRIPTION
**Pull request by hosmelq**
Use pushState instead of replaceState to properly navigate back and forward.

### CODE REVIEW

**Comment by jenkoian** [comment]
Thanks @hosmelq are you able to resolve the conflict? Will then give a quick once over locally and merge. The changes look good though 👍

**Comment by jenkoian** [comment]
Sorry @hosmelq I think I missed your commit and there has now been subsequent changes in master which mean another conflict, you mind picking up again? Would like to get this merged soon, thanks for your work on it 👍

**Comment by hosmelq** [comment]
FIxed.

**Comment by jenkoian** [comment]
Thanks for this @hosmelq. Been trying it out locally and it works great, with one exception. When navigating back and forward the head portion of the mark up seems to disappear (do a check, navigate back then navigate forward to reproduce). Now I can also replicate on the live site (albeit with different replication steps) so likely not an issue with this PR, but wondered if you could take a look?

**Comment by hosmelq** [comment]
Sure, I'll take a look this weekend :)

**Comment by jenkoian** [comment]
Cheers for this, have updated the app for 2017 so closing this, feel free to re-submit! 😃

**Pull request closed without merging**
