### PR TITLE
Updating pull PULL_REQUEST_TEMPLATE.md from issue #165

### PR DESCRIPTION
**Pull request by deneuv34**
Fixes issue #304 

Changes: I just updating Pull Request Template file into format that references on the issue.

Screenshots for the change: 
screenshot from 2018-10-04 00-17-21

If there is message still need to change, please let me know

### CODE REVIEW

**Comment by jenkoian** [comment]
Hmm the more I think about this the more I think maybe we just ditch it. The project is too small to require so much information and it could actually put people off, WDYT?

**Comment by deneuv34** [comment]
@jenkoian yeah, how about remove `Consideration` & `Solution` section? :thinking:

**Comment by jenkoian** [comment]
@deneuv34 thanks, happy to give that a go, just one last thing, do you think you can add a sentence reminding people to add themselves to the `humans.txt` file?

**Comment by deneuv34** [comment]
@jenkoian I don't know. I think it'll better if we give reminder on the contribution guideline, mostly people will read it before make PR. That's what I though, what do you think?

**Comment by jenkoian** [comment]
Yeah alright, will merge, thanks!

**Comment by deneuv34** [comment]
you're welcome

**Pull request merged**
